### ISSUE TITLE
Provide version of the meta validation schemas with .json extension

### ISSUE THREAD

**Issue by Anthropic** [json-schema-org/json-schema-org.github.io#108]
Discussed in #31 but really a separate issue, the schemas of the drafts not having an extension means they always download when a user clicks the link, sites like Schema Store which is linked to from Microsoft's VS Code link directly to the available schema which creates a less than ideal user experience. It is very frustrating when you want to view the schema to have to save it first and open it when it could have been viewed in the browser.

Given the files are in json format, I feel they should be duplicated with the json extension if they can't be renamed for whatever reason.

**Comment by handrews** [comment]
As discussed in #31, the correct solution is to set the content-type, which is a problem because we don't have control of the DNS.

**Comment by Anthropic** [comment]
Is @kriszyp not reachable? I thought it was only Nick that was unreachable?

**Comment by handrews** [comment]
He doesn't have access.  https://github.com/kriszyp/json-schema/commit/1c4923479501cdf78c6dab4e9af4bb40dc7992f0#commitcomment-19914120

We don't even know who has access, just that it's not anyone who was willing to answer email the last time anyone tried.

**Comment by benjagm** [comment]
Closing this issue as obsolete.
