### ISSUE TITLE
Contact easyDNS about domain transfer or recovery

### ISSUE THREAD

**Issue by adamvoss** [json-schema-org/json-schema-org.github.io#121]
Indicated in numerous issues is the fact that the controlling owner of the json-schema.org domain is unreachable though other people involved with the project have continued payment for the domain.  As suggested in https://github.com/json-schema-org/json-schema-org.github.io/issues/48#issuecomment-262309638 this is an issue to track contacting the registrar with respect to trying to gain control of the registration.

Since contact with the original owner is not expected at this point, the options would be to let the domain expire and hope to be able to buy it when it becomes available (risky) or to work with easyDNS support to try to reach a solution.

Regarding contacting easyDNS, see: https://fusion.easydns.com/Knowledgebase/Article/View/264/0/accountdomain-access-issues

> **Someone else created the account for us!**
> [...]
> If you are the owner of a domain (as displayed in the WHOIS information for the domain) but the domain is in an easyDNS account which is not in your name or under your control, we have a procedure in place for this as well.
> [...]
> If you are unable to contact the person or company in question, set up an account as mentioned above, and contact our support team by phone or email. We'll check proof of ownership through a series of procedures, then move the domain into your account. The process isn't immediate, as you might understand, and we appreciate your understanding in the matter.

@kriszyp Appears to be indicated on the [WHOIS record](https://whois.icann.org/en/lookup?name=json-schema.org), so they would likely have the easiest time with this.

**Comment by Relequestual** [comment]
Thanks for being proactive on this!

**Comment by kriszyp** [comment]
I thought @Mboyer did have control of the easyDNS account to make changes (https://github.com/kriszyp/json-schema/commit/1c4923479501cdf78c6dab4e9af4bb40dc7992f0#commitcomment-18474751). Or maybe I misreading that? I thought the issue was that no one had control of the github repo?

**Comment by Relequestual** [comment]
The issue was first the repo, then we discovered the domain also.

**Comment by handrews** [comment]
@Relequestual and I are in contact with the current owners of the domain.  I'll leave #80 open for tracking, but we don't need this issue anymore.
