### ISSUE TITLE
Disimbiguate similarly named implementations

### ISSUE THREAD

**Issue by adamvoss** [json-schema-org/json-schema-org.github.io#124]
I noticed while preparing #123 that there are numerous similarly named libraries listed on the [Software](http://json-schema.org/implementations.html) page.  For example [Java](http://json-schema.org/implementations.html#validator-java) has two implementations called "json-schema-validator"

I propose that when repositories have the same name, the user/org should be included to qualify which implementation is being referenced.  For example Java would become:

* Java
  * java-json-tools/json-schema-validator
  * everit-org/json-schema
  * networknt/json-schema-validator

**Comment by handrews** [comment]
I think we've covered this now
