### ISSUE TITLE
Visual Studio Code also support JSON Schema 

### ISSUE THREAD

**Issue by kanitw** [json-schema-org/json-schema-org.github.io#13]
Add it to the editor list in http://json-schema.org/implementations.html?

**Comment by awwright** [comment]
@kanitw Can you leave a Pull Request with some details, like a link?

**Comment by aeschli** [comment]
I created https://github.com/json-schema-org/json-schema-org.github.io/pull/72

**Comment by Relequestual** [comment]
Super. Thanks @aeschli - Did you find the issue based on the Available tag btw?

**Comment by aeschli** [comment]
@Relequestual Np, I didn't look for the 'Available' tag. A user of VSCode suggested that we should get added. See https://github.com/Microsoft/vscode/issues/18744

**Comment by Relequestual** [comment]
Thanks @aeschli, some interesting use cases there! I'd never consdiered JSON Schema for use in editing files of know formats... @handrews would you look at http://schemastore.org/json/ =]
