### ISSUE TITLE
Order by draft support?

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-org.github.io#155]
I'd really like to highlight/promote implementations that have updated to support new drafts.  How would folks feel abound changing the software page to group first by the most recent draft supported, then by the type of implementation, then by the language?

The great work @adamvoss has done splitting the data out into structured YAML should make this a lot easier.

@Relequestual any thoughts on this?  I think it would be good for people to see the availability of support without poring through the list for the draft support notes, and it might encourage implementations to update in order to get a more prominent spot on the page.

**Comment by Relequestual** [comment]
This makes sense.
I may even make some GH badges for readmes.

**Comment by handrews** [comment]
Badges would be cool!

**Comment by adamvoss** [comment]
I'd say the main downside would be maintenance effort since this would need to reset on every release.
#6 may be relevant or worth considering here.

If doing this, I would recommend two pages.  The current software link takes you to the page with current software, then either at the top or bottom of that page there would be a link to a page with older implementations.

**Comment by handrews** [comment]
@adamvoss that is a good plan.  It would give us more flexibility than a strict by-version list.  For instance drafts-06 and -07 should both be considered "current" for some time after we get draft-07 out the door.  Particularly for validation where the delta is quite small.  And we don't really need to keep track of who implements 3 vs 4 at the level of giving them separate pages.

Mostly, I want to highlight implementations that have moved on past draft-04, and make it *REALLY* obvious that the project is active again.  This would accomplish that.

**Comment by Relequestual** [comment]
Sounds like a reasonable plan.
If you mainy want to highlight those that support 5 or above vs 4 and below, then we could also on the main page have two groups. I still prefer @adamvoss's idea, but that's just another one for the sake of argument.

**Comment by handrews** [comment]
This has now been done
