### ISSUE TITLE
What is the repository for the website?

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-org.github.io#16]
It seems like this one should be the right one. But the website seems to be in sync with gh-pages branch of https://github.com/json-schema/json-schema...

So where do I update it?

**Comment by Relequestual** [comment]
Hey @epoberezkin , Totally aware of this issue.
It's currently proving difficult to get the domain redirected to the new repo...
(https://github.com/kriszyp/json-schema/commit/1c4923479501cdf78c6dab4e9af4bb40dc7992f0)
Plus a few emails between people... Not sure how to resolve this issue, let alone some bigger issues for the project.

/cc @awwright @Julian

**Comment by Julian** [comment]
What's the thing that still needs to be done? Wasn't there something other than the DNS change that just requires write on the other repo?

**Comment by awwright** [comment]
gh-pages branch of https://github.com/json-schema/json-schema should be deleted, but get ahold of me and @Relequestual on IRC so we can merge #7 after that's done.

**Comment by Relequestual** [comment]
Correct. I've check with GH support. Either that branch needs to be deleted, or we can claim ownership if https://github.com/kriszyp/json-schema/commit/1c4923479501cdf78c6dab4e9af4bb40dc7992f0 is inacted, but Kris isn't even sure if he has control over the domain anymore (someone is still paying for it at least).

What we also need is a redirection for people from the old repo to the new repo (considering github support have flat out refused to alter / restore ownership permissions). I previously suggested, although I'm not sure it was on a github issue, that setting an issue template and a contributing.md file for the old repo, would be the easiest way to direct people here.

**Comment by ShawnTalbert** [comment]
I just went through the trouble of updating THIS repo  so I hope it's the right place and will be reviewed by maintainers soon :)

**Comment by Relequestual** [comment]
@ShawnTalbert I have emailed you (in case your email on your profile is out of date) =]

**Comment by awwright** [comment]
This is the repository now, for sure.

Let me know if there's any further questions, thanks :)
