### ISSUE TITLE
Weird looking page

### ISSUE THREAD

**Issue by Semigradsky** [json-schema-org/json-schema-org.github.io#165]
Looks like some links ruined
http://json-schema.org/examples.html

---

![image](https://user-images.githubusercontent.com/1198848/31614683-e19f56c0-b28f-11e7-991e-db02b988ba1b.png)

**Comment by handrews** [comment]
@Semigradsky I think this is fixed now, let me know if there's still anything wrong and thanks for reporting this!

**Comment by Semigradsky** [comment]
Unfortunately, there is one more problem :smile_cat: #169

**Comment by adamvoss** [comment]
This is a manifestation of https://github.com/benbalter/jekyll-relative-links/issues/36
