### ISSUE TITLE
Example schemas links not working

### ISSUE THREAD

**Issue by Semigradsky** [json-schema-org/json-schema-org.github.io#169]
http://json-schema.org/examples.html

![image](https://user-images.githubusercontent.com/1198848/31931270-573a4518-b8ab-11e7-8744-e532e95510f1.png)

404 on
- Geographic Coordinate - http://json-schema.org/geo.json
- Card  - http://json-schema.org/card.json
- Calendar - http://json-schema.org/cal.json
- Address - http://json-schema.org/addr.json

**Comment by handrews** [comment]
@Semigradsky are you actually using these for anything?  Just noticing more oddities, and noticing that they weren't even linked on the last version of the site (they were on the version before that- this is at least the 3rd major iteration of the web site that I know of)

**Comment by handrews** [comment]
Forgot to close this when I merged #170 several weeks ago.
