### ISSUE TITLE
Do the four example schemas belong here?

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-org.github.io#171]
Why are we hosting the geo, address, calendar, and card schemas?  In the previous iteration of the site they were not linked, as far as I can tell.  I kind of remember that they weren't linked on this one until recently.  They have several oddities, like a lack of `$id` (except one which has `id` despite declaring a draft-06 `$schema`).

I don't think that we should really be a registry of "standard" schemas, particularly a we barely have bandwidth to maintain the web site and have not been able to update the examples as it is.  We certainly don't have time to maintain an extensible registry, and this small selection is pretty random.

How do people feel about removing these?  Apologies if this came up before, I wasn't paying as much attention and there was a lot of noise in some of those issues so I'm not going through and reading them all again.

@Relequestual @awwright @adamvoss @Semigradsky @epoberezkin @Julian

**Comment by adamvoss** [comment]
* People learning or exploring a technology want to see examples, from that perspective, they have value.
  - We could potentially direct them to http://schemastore.org/json/ to see examples, but that may not be as nice of experience.
* One of the examples (geo I believe) referenced from the walk-through schema so that be a dangling reference if removed.

I agree about not being a list of standard schemas, I know I have posts on that somewhere.  I don't think I ever got a direct response on that point but changes I made via PR to to the website to try to down-play that suggestion in how they were presented did get merged.

**Comment by handrews** [comment]
Thanks, @adamvoss 

I probably should not have used the word "examples" in this title.  Because if anything, we need better examples and tutorials.  

But (aside from using geo in the walk-through, apparently) these aren't presented as educational examples, but as items for re-use.  I wouldn't necessarily mind keeping them, but I think the current presentation, even the de-emphasized version (and thanks for that) gives the wrong impression.

Linking to some existing schema archives (even just one) seems pretty reasonable.

**Comment by handrews** [comment]
I think part of this is that I was about to assign `$id` values to the schemas, and then thought "if these have ids under http://json-schema.org, then a lot of people are going to think they are some official set of schemas" which I'm pretty sure we don't want

**Comment by Relequestual** [comment]
I think there is value in linking to shcemastore!
It's a shame we don't have JSON Schema versions of the schemas on schema.org

**Comment by handrews** [comment]
We do have [a link to schema store](http://json-schema.org/implementations.html#schema-repositories)

I'd still like to consider dropping the examples.  Or, rather, if they are useful as examples making them inline blocks within the example/tutorial page instead of real-looking schemas with URIs.

As noted in https://github.com/SignalK/specification/issues/457, the GeoJSON example doesn't even match the final RFC (there is a compliant one on schemastore.org, though!).  And even with them under `example`, hosting them here still makes them look rather official.

@Relequestual @awwright @philsturgeon current thoughts?

**Comment by handrews** [comment]
Fixed by PR #215 back in June.
