### ISSUE TITLE
Travis build failing b/c draft-06 meta schema is somehow a duplicate

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-org.github.io#175]
I suspect some sort of change in ajv/ajv-cli that now automatically recognizes draft-06 where before we needed to pass it explicitly.

@epoberezkin did this change at all recently?

**Comment by handrews** [comment]
Example failure https://travis-ci.org/json-schema-org/json-schema-org.github.io/builds/303113420?utm_source=github_status&utm_medium=notification

I've reproduced it locally.  Depending on the ajv-cli version I either get this error or it doesn't understand draft-06f, but I suspect I'm missing something and have not thoroughly checked all possible versions.

**Comment by epoberezkin** [comment]
I will look today

**Comment by epoberezkin** [comment]
@handrews it's been like this for a long time, since ajv-cli 2.0 (April). draft-06 schema is included by default.

**Comment by handrews** [comment]
@epoberezkin weird.  And now I can't reproduce it on my work laptop (was on my personal one earlier).  I'll keep poking at it.  Thanks for checking it out on your end, good to eliminate that possibility.

**Comment by handrews** [comment]
This seems to have worked itself out.  Let's just move on ¯\_(ツ)_/¯
