### ISSUE TITLE
Update meta-schema link

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-org.github.io#178]
It still points to draft-06 here: http://json-schema.org/documentation.html

Also I thought we've agreed not to use version-less URLs: http://json-schema.org/schema ?

**Comment by handrews** [comment]
Ugh, I thought so, too.  I suspect someone will freak out if we remove them.  But I will change the links on that page to point to the ones with draft-07 in the URL at least.

**Comment by handrews** [comment]
Fixed.
(I haven't been doing PRs for mechanical draft-07 updates)
