### ISSUE TITLE
Build fails after ajv update to v6 / draft-07

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-org.github.io#185]
The build: https://travis-ci.org/json-schema-org/json-schema-org.github.io/builds/327592609

The reason the build fails after ajv update is that now draft-07 meta-schema is already added to the ajv instance and it is slightly differently defined in ajv than in the spec (the latest change in the spec was to replace empty schemas with `true`).

I will update the meta-schema in ajv and the issue will go away, but in general the test here needs to be updated to do one of the following:
- replace validations against meta-schema, e.g. `ajv test -s schema -d "_includes/person.json" --valid` with `ajv compile -s _includes/person.json` (that will validate against meta-schema by default).
- do not add meta-schema to the instance: `ajv test -s schema -d "_includes/person.json" --valid --meta=false --validate-schema=false`.

cc @Relequestual

**Comment by epoberezkin** [comment]
The test is defined here: https://github.com/json-schema-org/json-schema-org.github.io/blob/master/.travis.yml

**Comment by epoberezkin** [comment]
It is also worth fixing a major version of ajv-cli by using `npm install ajv-cli@3` instead of `npm install ajv-cli` (or by adding package.json).

**Comment by epoberezkin** [comment]
So the build passes now but if the draft-07 meta-schema is updated in json-schema-org the test will fail again, so some of the changes above still needs to be made if such update is possible.

**Comment by Relequestual** [comment]
@adamvoss as you set this up, does the suggested changes make sense to you? I'm not familiar with the test setup to know.

**Comment by Relequestual** [comment]
Thanks for looking into this @epoberezkin  =]
