### ISSUE TITLE
Update examples to contain draft-7 features

### ISSUE THREAD

**Issue by omniproc** [json-schema-org/json-schema-org.github.io#187]
Would be awesome if someone could include some of the new draft-7 features into the examples. E.g. I'm highly interested in the actual use of if / then / else but can't find any examples.

**Comment by handrews** [comment]
@m451 yeah that would be great.  We're very short on people to add to the actual content of the site- there aren't that many of us actively working on the spec and it tends to suck up all of the time (also, for me personally, my inability to write examples that anyone finds useful is a bit of a running joke in the spec development issues).  If you know of or encounter anyone who is good at examples and tutorials please encourage them to reach out to us about adding content.

In the meantime, we have a slack channel that is good for asking questions.  Here's the invite link from the bottom of the front page of our site: https://join.slack.com/t/json-schema/shared_invite/enQtMjk1NDcyNDI2NTAwLTcyYmYwMjdmMmUxNzZjYzIxNGU2YjdkNzdlOGZiNjIwNDI2M2Y3NmRkYjA4YmMwODMwYjgyOTFlNWZjZjAyNjg

**Comment by benjagm** [comment]
Closed as not planed. We are focusing our efforts in the documentation of the current version of the Spec.
