### ISSUE TITLE
Add dependency on a "child property"

### ISSUE THREAD

**Issue by AdityaTulasi** [json-schema-org/json-schema-org.github.io#191]
Hi,

I want to add a dependency on presence of a property _inside_ an object that is at the same level.

Example
```
{
    "Name": "Something", 
	"Data": {
        "Somekey1": "Some value"
    }
}
```

I need "Name" to be conditionally present, and it should depend on presence (or value of; hierarchy is the primary concern here) of ```Somekey1```. Is this possible? If yes, can you please tell me the JSON schema for this?

Thanks.

**Comment by chulkilee** [comment]
Please use https://github.com/json-schema-org/json-schema-spec
