### ISSUE TITLE
Travis failing b/c of icon-github.html

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-org.github.io#197]
We're not even referencing this thing, I have no clue why it's suddenly not working

https://travis-ci.org/json-schema-org/json-schema-org.github.io/builds/355658613

$ bundle exec jekyll build
Configuration file: /home/travis/build/json-schema-org/json-schema-org.github.io/_config.yml
            Source: /home/travis/build/json-schema-org/json-schema-org.github.io
       Destination: /home/travis/build/json-schema-org/json-schema-org.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Could not locate the included file 'icon-github.html' in any of ["/home/travis/build/json-schema-org/json-schema-org.github.io/_includes", "/home/travis/.rvm/gems/ruby-2.4.1/gems/minima-2.4.0/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in /_layouts/default.html
jekyll 3.6.2 | Error:  Could not locate the included file 'icon-github.html' in any of ["/home/travis/build/json-schema-org/json-schema-org.github.io/_includes", "/home/travis/.rvm/gems/ruby-2.4.1/gems/minima-2.4.0/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.
The command "bundle exec jekyll build" exited with 1.

**Comment by handrews** [comment]
I committed my local Gemfile.lock as it works and that is apparently best practice anyway.  Now the error is:

Incremental build: disabled. Enable with --incremental
      Generating... 
             Error: could not read file /home/travis/build/json-schema-org/json-schema-org.github.io/vendor/bundle/ruby/2.4.0/gems/jekyll-3.6.2/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.4.0/gems/jekyll-3.6.2/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.4.0/gems/jekyll-3.6.2/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
The command "bundle exec jekyll build" exited with 1.

I don't know what to do with this.  Have I mentioned before how much I hate Jekyll and the entire GitHub pages infrastructure?  I'd really rather just write HTML.  It's not like our site is complicated.

**Comment by handrews** [comment]
We're not even using the blog feature

**Comment by Relequestual** [comment]
Fixed by https://github.com/json-schema-org/json-schema-org.github.io/commit/6bfb460102cb30eef1aba0a8b671ae5b5dcbd296
