### ISSUE TITLE
Official IRC channel

### ISSUE THREAD

**Issue by Acubed** [json-schema-org/json-schema-org.github.io#2]
We've got #json-schema on Freenode now. We should link to this on the website.

**Comment by Relequestual** [comment]
+1

**Comment by g-giani** [comment]
#json-schema is set to invite only. Why is it? Who should be msg for invite?

**Comment by Relequestual** [comment]
You just need to have a registered account with a password. I don't believe it's invite only. This was done to prevent spam.

**Comment by Relequestual** [comment]
Besides, we don't really use the irc much anymore. The Slack server is far more active!

**Comment by ssbarnea** [comment]
To help others that may wonder where to join https://join.slack.com/t/json-schema/shared_invite/zt-nv0vbdfq-Ba_zz2cZBe_26ZoU7fEYGg

**Comment by Relequestual** [comment]
We actually set up https://json-schema.org/slack in case the invite needs updating
