### ISSUE TITLE
Generators section includes github.com/qri-io/jsonschema which does not support generation

### ISSUE THREAD

**Issue by gaffo** [json-schema-org/json-schema-org.github.io#210]
github.com/qri-io/jsonschema supports going from a golang object TO a schema / json... however it does not actually generate go code which would represent a given struct. So I don't believe it should actually live in this section.

**Comment by handrews** [comment]
Thanks, @gaffo, the note for this implementation in the old page layout said something like "codes to and from go" which sounded like it went both ways (and I couldn't immediately tell from the five seconds I spent glancing at the README- too many projects for me to dig through them in detail).

I'll update this.

**Comment by handrews** [comment]
Should be fixed now- thanks!
