### ISSUE TITLE
json-schema.org’s server IP address could not be found.

### ISSUE THREAD

**Issue by jackwootton** [json-schema-org/json-schema-org.github.io#213]
This site can’t be reached
json-schema.org’s server IP address could not be found.
Search Google for json schema org examples
ERR_NAME_NOT_RESOLVED

![dexkzzwucaiik83](https://user-images.githubusercontent.com/1623996/40888076-e8c8eb18-6749-11e8-934f-5ccb932c8d2a.jpg)

**Comment by chulkilee** [comment]
`whois json-schema.org`

```
Domain Name: JSON-SCHEMA.ORG
Registry Domain ID: D149869816-LROR
Registrar WHOIS Server: whois.easydns.com
Registrar URL: http://www.easydns.com
Updated Date: 2018-05-29T21:35:57
Creation Date: 2011-12-05T12:15:59
Registrar Registration Expiration Date: 2018-11-20T18:11:51
Registrar: easyDNS Technologies, Inc.
Registrar IANA ID: 469
Domain Status: clientHold https://icann.org/epp#clientHold

>>> Last update of WHOIS database: 2018-05-29T21:35:57 <<<
```

**Comment by chulkilee** [comment]
Until `json-schema.org` DNS configuration is fixed.. I added ip address of `json-schema-org.github.io` to `/etc/hosts`.

```
# temporary records: json-schema.org => json-schema-org.github.io
# see https://github.com/json-schema-org/json-schema-org.github.io/issues/213
185.199.108.153  json-schema.org
```

**Comment by Relequestual** [comment]
I'll try to get to the bottom of this!
Thanks for letting us know.

**Comment by handrews** [comment]
@Relequestual resolved this- we had tracked down who owned the domain (see https://github.com/json-schema-org/json-schema-org.github.io/issues/80#issuecomment-391185067 ) and were working with them to get things sorted out, and something went a bit wrong with the transfer.  That's been fixed and the site is back up.
