### ISSUE TITLE
Support and Enforce HTTPS

### ISSUE THREAD

**Issue by oboukli** [json-schema-org/json-schema-org.github.io#216]
Now that [GitHub Pages with custom domains support HTTPS](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/), support for the HTTPS scheme should be added and enforced.

Do we need HTTPS? Yes. See https://doesmysiteneedhttps.com/

Once enabled, I'm happy to create a pull request to update the links on the website.

**Comment by handrews** [comment]
We know.  GitHub does not support our current DNS configuration.  The story with the domain is very complicated, please follow #80 for this topic.
