### ISSUE TITLE
Restrict properties in $ref

### ISSUE THREAD

**Issue by BigDataKatha** [json-schema-org/json-schema-org.github.io#218]
After researching and reading [documentation](https://spacetelescope.github.io/understanding-json-schema/structuring.html), I couldn't find the answer to how I can use $ref in order to keep consistency between object fields, but only display required fields.

For example, the device object is:
````
{
  "category": "Mobile",
  "screenResolution": "360x600",
  "mobileBranding": "Apple",
  "mobileModel": "iPhone",
  "mobileName": "iPhone 6",
  "operatingSystem": "iOS",
  "operatingSystemVersion": "9",
  "isMobileApp": true
}
````

Referencing the device object in another object, I require only category, screenResolution, and operatingSystem from the original object:

````
"device": {
      "allOf": [
        {"$ref": "./device.schema.json"},
        {"required": ["category", "screenResolution", "operatingSystem"]}
      ],
      "additionalProperties": false
    }
````

It seems that the issue of [overriding earlier object specifications](https://github.com/OAI/OpenAPI-Specification/issues/556) hasn't been solved?

**Comment by handrews** [comment]
@BigDataKatha the spacetelescope book only covers draft-04, which is now over five years old (we're on draft-07 now, although the actual IETF numbering situation is complicated).

The `$ref`-related things that I linked to in that OpenAPI issue you linked are part of the forthcoming draft-08.

Without seeing your "./device.schema.json" schema I can't quite tell what you are trying to do here.  Are you trying to add a `required`, change `required`, or actually remove/forbid properties from there in the referring location?

BTW, discussions about how to use JSON Schema are best done on the [slack workspace's general channel](https://join.slack.com/t/json-schema/shared_invite/enQtMjk1NDcyNDI2NTAwLTcyYmYwMjdmMmUxNzZjYzIxNGU2YjdkNzdlOGZiNjIwNDI2M2Y3NmRkYjA4YmMwODMwYjgyOTFlNWZjZjAyNjg) if possible.  This repository is for issues with the web site.

**Comment by Relequestual** [comment]
@BigDataKatha draft-8 will specify that $ref no longer effects other properties in the same object.
Are you happy to close this issue or do you want to wait till we release draft-8 and update the website / learn section to reflect this change?

**Comment by BigDataKatha** [comment]
@handrews I am trying to remove properties. How can this be achieved?
@Relequestual . What do you mean with "$ref no longer effects other properties in the same object". I am ok to close this issue and move to Slack. Do you recommend for me to ask the same question again there?

**Comment by Relequestual** [comment]
You can't remove properties, that just isn't going to happen. In stead, you need to consider how you can segment and combine using `$ref` inside `allOf`.

That linked OpenAPI issue, currently (draft-7) any use of `$ref` removes any sibling key words at the $ref's location. In draft-8, this will no longer be true.

**Comment by handrews** [comment]
No further discussion since July, and this is better addressed on slack (there's a join link on json-schema.org) or stackoverflow anyway.  Closing.
