### ISSUE TITLE
Remove example files no longer in use

### ISSUE THREAD

**Issue by Anthropic** [json-schema-org/json-schema-org.github.io#226]
There was a PR #221 that has left four schema in the root (**address, calendar, card, geo**) that appear to serve no purpose as they now link to empty object schemas. I think we need to decide to either remove them completely or alter the links to their new location within the learn folder.

My first attempt to update the symlinks #225 failed CI so i closed it, so not sure what went wrong but seems updating symlinks has more to it anyway.

Am I correct in assuming that we all tend to lean toward delete?

@philsturgeon @handrews @Relequestual

**Comment by retrosight** [comment]
I've created a pull request which removes them -- it has failed so perhaps we will have data that tells us exactly why within the CI system.

**Comment by retrosight** [comment]
```
jekyll 3.7.3 | Error:  No such file or directory @ realpath_rec - /home/travis/build/json-schema-org/json-schema-org.github.io/example
```

**Comment by retrosight** [comment]
There is another error further up the log but I don't think it's related.

**Comment by Anthropic** [comment]
@retrosight the schemas are referenced in the symlink files in root
https://github.com/json-schema-org/json-schema-org.github.io/blob/master/address
https://github.com/json-schema-org/json-schema-org.github.io/blob/master/card
https://github.com/json-schema-org/json-schema-org.github.io/blob/master/calendar
https://github.com/json-schema-org/json-schema-org.github.io/blob/master/geo

**Comment by retrosight** [comment]
Well, what appears in the clone of the repository...

```
{}
```

...and what appears in the GitHub UI...

```
example/address.json
```

...are very different.

**Comment by retrosight** [comment]
Trying `git rm {file}` now.

**Comment by charlieconcur** [comment]
That did the trick -- the CI process is now succeeding.

**Comment by Anthropic** [comment]
@retrosight it is a linux symlink, the file is a pointer and the current pointer is to `example/address.json` and the content of that file is `{}`

**Comment by retrosight** [comment]
Yup. It's fixed.

**Comment by retrosight** [comment]
@philsturgeon @handrews @Relequestual Should be an easy merge.

**Comment by handrews** [comment]
@retrosight @Anthropic thanks!
