### ISSUE TITLE
Consider including extended child validation examples

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-org.github.io#25]
The following was originally written by @fge at 
https://github.com/json-schema/json-schema/wiki/Determining-what-schemas-an-object-member-value-should-validate-against
https://github.com/json-schema/json-schema/wiki/Determining-what-schema-an-array-element-should-validate-against

It goes into greater detail on child schema validation than fits into the specification proper:

# Object properties

## Implied keywords

For one object member, the set of schemas which the associated value must be valid against depends on the member itself and the following keywords:

* <tt>properties</tt>,
* <tt>patternProperties</tt>,
* <tt>additionalProperties</tt>.

**NOTE:** the default value for these keywords is an empty object (which MUST be considered as an empty schema for <tt>additionalProperties</tt>).

**NOTE 2:** in the text below, the following terminology will be used:

* the _member_ is the object instance member's name;
* the _value_ is the value associated with that member.

## Algorithm

We start with an empty set of schemas, which we will call <tt>s</tt>.

### Schemas from <tt>properties</tt>

If one member of the <tt>properties</tt> keyword value has the same value than the target member, the corresponding value of <tt>properties</tt> is added to <tt>s</tt>.

### Schemas from <tt>patternProperties</tt>

For the recall: members of <tt>patternProperties</tt> are ECMA 262 regular expressions (see [pattern](pattern)). For convenience, these members will be referred to as _regexes_ from now on.

For each regex, if it matches the target member successfully, then the value associated to that regex is _also_ added to <tt>s</tt>.

**This means that several schemas may be added to the set at this step!**

### <tt>additionalProperties</tt>

At this stage, the value of <tt>additionalProperties</tt> is added to the set **if and only <tt>s</tt> was previously empty**.

## Example

(note: the set <tt>s</tt> above will be materialized as a JSON array in this section)

Consider this schema:

```json
{
    "type": "object",
    "properties": {
        "p1": { "type": "string" }
    },
    "patternProperties": {
        "p": { "minLength": 10 },
        "1": { "format": "host-name" }
    },
    "additionalProperties": {
        "disallow": "boolean"
    }
}
```

And this object instance:

```json
{
    "p1": "json-schema.org",
    "p2": "slippery slope",
    "x": null
}
```

### For member <tt>p1</tt>

* <tt>properties</tt> in the schema has a member by the same name. The associated schema is therefore added to the set which is now:

```json
[ { "type": "string" } ]
```

* both regexes in <tt>patternProperties</tt> successfully match <tt>p1</tt>, so schemas associated with _both_ of these regexes are added to the set, which is now:

```json
[ { "type": "string" }, { "minLength": 10 }, { "format": "host-name" } ]
```

* the set is not empty at this point, therefore we don't need to add the schema associated with <tt>additionalProperties</tt>. The final set of schemas which the value must validate against is therefore:

```json
[ { "type": "string" }, { "minLength": 10 }, { "format": "host-name" } ]
```

### For member <tt>p2</tt>

* there is no member by the same name in <tt>properties</tt>. At this step, the set is therefore empty:

```json
[]
```

* regex <tt>p</tt> matches <tt>p2</tt> successfully, not regex <tt>1</tt>. The schema associated with regex <tt>p</tt> is therefore added to the set:

```json
[ { "minLength": 10 } ]
```

* as in the previous example, as the set is not empty at this point, <tt>additionalProperties</tt> needs not be considered; the final set of schemas which the value must validate against is therefore:

```json
[ { "minLength": 10 } ]
```

### For member <tt>x</tt>

* there is no member by the same name in <tt>properties</tt>. At this step, the set is therefore empty:

```json
[]
```

* none of the regexes in <tt>patternProperties</tt> match <tt>x</tt> successfully. The set is _still_ empty:

```json
[]
```

* the set being empty at this point, this time, the schema associated with <tt>additionalProperties</tt> must be added; the final set of schemas which the value must validate against is therefore:

```json
[ { "disallow": "boolean" } ]
```

# Array Elements

## Implied keywords

For one array element, the schema which this element must validate against depends on its index in the array and the following keywords:

* <tt>items</tt>,
* <tt>additionalItems</tt>.

**NOTE**: array indices start at 0.

## If <tt>items</tt> is absent

If <tt>items</tt> is absent, its default value is the empty schema. Which means all elements are valid. The end ;)

## If <tt>items</tt> is an object</tt>

In this case, all elements of the array instance MUST be valid against the <tt>items</tt> keyword value, which is a JSON Schema.

## Otherwise: <tt>items</tt> is an array

If this is an array, then the schema is determined by the index of the array element to validate. There are two possibilities:

### The element index is less than, or equal to, the highest index in the <tt>items</tt> array

In this case, the element MUST be valid against the schema found at the given index in the <tt>items</tt> array.

### The element index is greater than the highest index in the <tt>items</tt> array

In this case, it depends on the value of <tt>additionalItems</tt>:

#### If <tt>additionalItems</tt> is boolean <tt>true</tt>, or absent

This is equivalent to <tt>additionalItems</tt> being an empty schema, which means the element always validates successfully.

#### If <tt>additionalItems</tt> is an object

If it is an object, then by the rules, it is a valid JSON Schema. In this case, the element MUST validate successfully against that schema.

**Comment by Relequestual** [comment]
I find this language very confusing and difficult to read. After a while, I understood the first section. I still don't understand the final section.

Personally, I feel most of the specification could benefit from being defined in the following format:
- Use case
- Example
- Technical definitions

Wherein the technical definitions section is what results in constituting the specification document.

Once I read the example, the technical definition made much more sense. I feel understanding should be grounded in context and example.

**Comment by handrews** [comment]
I think this approach to the language comes from the desire in Draft 04 to separate the validation of the structure of an array or object from the validation of the data within array elements or object properties against the relevant child schemas.  Which resulted in (to me) counter-intuitive statements like "if `items` is an object, then validation of the instance always succeeds" in the array validation section.  That sort of language was in sections in the middle of the document, while the more terse form of this algorithm that addressed the need to validate against the child schemas is in a section at the end.

It's not clear to me why the specification went to such lengths to keep these things separate, but I feel like it made comprehending JSON Schema much more difficult.

**Comment by awwright** [comment]
@handrews Is this an issue against the website?

**Comment by handrews** [comment]
I thought the web site was where to file requests for more examples / more in-depth explanation.  I'm trying to finish the "migrate the old wiki" issue so I've been looking at pages about existing features and either marking them incorporated, or (if they have more information that does not seem to be captured elsewhere) filing them as web site bugs.

I'm totally fine with closing this and not doing anything with it, I just want to make sure we choose to do stuff like that rather than just forgetting about it on the wiki.

I'm happy to do something else with these sorts of pages if you'd prefer.

**Comment by awwright** [comment]
@handrews Specific changes should probably be done by PR, unless it's a major change that would benefit from discussion first. I'm not sure which category this falls into.

In any event, the website also needs some organization, too. Whatever content we have here I'd say should be integrated into the respective sections of the website... if any. I'm working on a rewrite right now where that'll be easier.

Overall, if it's just a piece on "how to use JSON Schema", I'd say ignore it/close it.

**Comment by handrews** [comment]
@awwright that works for me. I will just mark such old wiki pages as "folded into the website" or something along those lines.  Really I just need to be able to mark which ones I've looked at.  I don't plan on actively trying to do PRs for all of the explanatory content as I have more than enough to do with just the specification aspects right now.

**Comment by Relequestual** [comment]
I was thinking about possibly keeping this one open, but that's fine. However we can create functionality lists and attempt to explain all parts of the schema in the documentation on the site. *looks at githubs new project functionality*

**Comment by handrews** [comment]
@Relequestual was there something specific you wanted from this particular wording?  I think we all agree that it's a confusing presentation of the concepts.  I think if Austin's cleanup of what's now draft 05 makes this easier to follow in the specification we might not need any of this anyway.

But if there's something specific about this area you want addressed it might be worth filing as its own issue if it's not tied to this language.

**Comment by Relequestual** [comment]
@handrews in which case, keep it closed. If you feel draft 5 chanegs make it easier to understand, I'll take your word for it.
