### ISSUE TITLE
JSON Relative Pointer confusing link

### ISSUE THREAD

**Issue by Eomm** [json-schema-org/json-schema-org.github.io#255]
Hi,
in the home page of the site, there is the link to the JSON Relative Pointer.

After reading the standard I understand that this spec is discouraged and not supported as well.

[the spec core](https://tools.ietf.org/html/draft-handrews-json-schema-01#section-8.2.3) says

> The effect of using a fragment in "$id" that isn't blank or doesn't follow the plain name syntax is undefined

[the json relative pointer itself](https://tools.ietf.org/html/draft-handrews-relative-json-pointer-01#section-6) says 
> Unlike a JSON Pointer, a Relative JSON Pointer can not be used in a URI fragment identifier.

So why there is that link in the home page? Could it be consider only confusing? Because it took me in the wrong path 😅

Thank you for you help

here the source of my consideration that I reported here https://github.com/fastify/fastify/issues/1419#issuecomment-459872495

**Comment by handrews** [comment]
JSON Relative Pointer is maintained by this project, and is used in JSON Hyper-Schema.

As noted in both the JRP spec and the JSON Schema core spec, JRPs are not valid URI fragments.  They are part of the project for other features.

**Comment by Eomm** [comment]
All clear now! 
Thank you very much for your time 👍🏼
