### ISSUE TITLE
Slack Invite Link Expired

### ISSUE THREAD

**Issue by Bialogs** [json-schema-org/json-schema-org.github.io#282]
The invite link to Slack on the main json-schema.org page seems to be expired

**Comment by Relequestual** [comment]
Boo! I'll get on that!

**Comment by Relequestual** [comment]
https://join.slack.com/t/json-schema/shared_invite/enQtNjc5NTk0MzkzODg5LTVlZGIxNmVhMGY2MWFlYTdiNDQ5NWFiZGUwOThhNmYxZDE0YzA5YjRiOTA5MGY4ZTZlZGZhZDFmYTY4NWM2N2Y
FYI

**Comment by Relequestual** [comment]
Updated. When you see it on the site, please close the issue =]

**Comment by Bialogs** [comment]
Certainly. Thanks for the prompt reply.

**Comment by Bialogs** [comment]
Following up: the link on json-schema.org is still not updated.

**Comment by handrews** [comment]
@Bialogs it was changed in one place but not the other two.  They should all be fixed now (header, footer, and one in the front page text).
