### ISSUE TITLE
question: how to add a new Language validator

### ISSUE THREAD

**Issue by membphis** [json-schema-org/json-schema-org.github.io#293]
here is my project, it base on Lua:

https://github.com/iresty/lua-resty-jsonschema

there was no Lua now:

![image](https://user-images.githubusercontent.com/6814606/67350970-e6e59200-f57e-11e9-9857-9ba2f58c44d3.png)

**Comment by Relequestual** [comment]
Modify this file to add the langauge:
https://github.com/json-schema-org/json-schema-org.github.io/blob/master/_data/validator-libraries-modern.yml

Then add your implementation to the list.
Do this on a fork and then make PR, and you'll get a build preview of the whole site. No need to install everything locally if that's a lot of effort.

**Comment by membphis** [comment]
many thx, I have submitted a PR right now: https://github.com/json-schema-org/json-schema-org.github.io/pull/294/files
