### ISSUE TITLE
Shouldn't the file pointers be changed?

### ISSUE THREAD

**Issue by forresst** [json-schema-org/json-schema-org.github.io#296]
Since the publication of the new version (the current version is 2019-09), shouldn't the file pointers be changed? As it was done for the change from draft-06 to draft-07 version [by this commit](https://github.com/json-schema-org/json-schema-org.github.io/commit/0f31052fbfaee99b9a0fa128b5748e4b912e802d).

Currently the following urls point to the draft-07 version:
- [https://json-schema.org/schema#](https://json-schema.org/schema#)
- [https://json-schema.org/hyper-schema#](https://json-schema.org/hyper-schema#)
- [https://json-schema.org/links#](https://json-schema.org/links#)

Maybe it's done on purpose?

**Comment by Relequestual** [comment]
Good spot. I think we just missed this.
I'll check with the rest of the team.
In the meantime, if you have time, feel free to file a PR =]

Thanks!

**Comment by forresst** [comment]
@Relequestual PR Done!

I'll let you check with the team. Thanks.

**Comment by handrews** [comment]
This has been resolved per PR #300
