### ISSUE TITLE
Website is pointing to the wrong Git repository

### ISSUE THREAD

**Issue by ReactiveRaven** [json-schema-org/json-schema-org.github.io#3]
As per https://github.com/json-schema-org/json-schema-spec/issues/10 :

The json-schema.org homepage (and http://json-schema-org.github.io/ ) points to [json-schema/json-schema](https://github.com/json-schema/json-schema), where it should point to [json-schema-org/json-schema-spec](https://github.com/json-schema-org/json-schema-spec).

**Comment by Relequestual** [comment]
I thiknk the intension is to only point to this repo "when it's/we're ready to do so". But it's unclear what that even means. There's a huge lack of leadership / direction on this project =[ It's totally unclear what the status is from those in control of the IETF draft documents.

**Comment by nemesisdesign** [comment]
Is there anyone with commit access active on this repository?

**Comment by Relequestual** [comment]
@nemesisdesign I have commit access.

**Comment by nemesisdesign** [comment]
Great to know @Relequestual, people like me have been going to the other repository and wrote entire proposals and discussion there. I also read in the description of https://github.com/json-schema-org:

"A replacement (hopefully temporary) for the json-schema organisation".

So it's not really clear what's the right thing to do. Wait for the original authors to come back and help or proceed in changing the links and moving the discussion on the new org?

Is anyone in contact with the people currently missing in action to know their opinion?

**Comment by Relequestual** [comment]
You've hit the nail on the head there. No one really knows what the best thing to do is, or how long we should wait for what to happen.

The guy in control of the json-schema organisation on github has been uncontactable for years now. Github will not give up control to other members. Policy. No exceptions. =[

It's not clear if issues should be migrated or not. It's not even clear who's running the show now, and even those who we may speculate are running the show (even here), may not be interested anymore. It's just impossible to tell when people won't communicate. There's some discussion on these issues going on (for the nth time) on the google group. I'm starting to loose it =[

**Comment by Acubed** [comment]
@ReactiveRaven This should be fixed now, if the website looks all good you can close this issue out. Thanks!

**Comment by ReactiveRaven** [comment]
Thanks :)

**Comment by adamvoss** [comment]
> The guy in control of the json-schema organisation on github has been uncontactable for years now. Github will not give up control to other members. Policy. No exceptions. =[

@Relequestual How does that policy interact with the [Name Squatting Policy](https://help.github.com/articles/name-squatting-policy/)?  There is recent activity in the other org, but that was only changes to indicate that the new home is here, so you might still be able to make the case that the other is abandoned and a source for brand confusion, while this org is clearly active in developing the JSON Schema name.

If nothing can be done there, it would probably be good to remove the "(hopefully temporary)" message to stop future onlookers (like me :-P) from questioning it.

**Comment by Relequestual** [comment]
Interesting though. Feel free to ping github support refernecing your comment here. They may want to corss refernece your request with my previous support tickets to better understand the full picture. It's not exactlay squatting, but does come under the guise of inactive, bar one or two changes for the domain name issues.

**Comment by Relequestual** [comment]
However, we can't claim "brand confusion" without having a trademark, I believe is their rules.
