### ISSUE TITLE
Links to standard (card, calendar, geo) schemas incorrect

### ISSUE THREAD

**Issue by evert** [json-schema-org/json-schema-org.github.io#31]

**Comment by Relequestual** [comment]
Where exactly? Looks like they are valid on the home page and in one of the examples for me.

**Comment by evert** [comment]
The links in the bottom here:

http://json-schema.org/documentation.html

Link to stuff like this:

http://json-schema.org/geo

Opening that link in firefox at least shows it as a `BIN file`, and looking in the developer console I'm getting a hexadecimal sequence for some reason.

Inspecting it further: not sure why I'm getting the weird output in firefox, but if I try that url with curl I did notice an incorrect mime-type, which is probably the root cause for the weirdness.

**Comment by Relequestual** [comment]
I'm using Firefox and not experiencing that problem. It opens as a text file for me when downloaded.

**Comment by evert** [comment]
@Relequestual that's surpising as the `Content-Type` is wrong and there's no standard file extension, and no `Content-Disposition` with some hint as to how a browser should handle a download. Given those facts, a browser treating those links as text-files would actually be the unexpected behavior ;) See `curl -v http://json-schema.org/geo` to double-check.

My browser is a fairly stock firefox browser. I can't imagine I'm alone.  How about fixing `Content-Type` for a slightly saner response?

**Comment by Relequestual** [comment]
@evert Hum. For my version of firefox, it downloads as standard, and suggests opening as text.
I'm not sure how I would go about setting the content type for the file beyond appending `.json` to the filename.
Pull request welcome if you know a different way.

**Comment by evert** [comment]
Ah I didn't realize you were using Jekyll. In that case I would indeed argue that you should add .json to these files to force a correct mime-type. I'd be happy to submit a PR for this if you'd like.

**Comment by Relequestual** [comment]
If you wouldn't mind, that would be helpful. I don't have the time today (or this week) to checkout the repo to make this change site wide. Thanks =]

**Comment by awwright** [comment]
@evert The URIs were purposefully selected to not use filename extensions, and we can't really change them without breaking things

Are you aware of any way to send a 200 with `Content-Type: application/schema+json` with Jekyll?

**Comment by evert** [comment]
@awwright jekyll *just* generates files. It's a static file generator and thus has no control over content-types. It's not aware of HTTP at all. Basically your two options are:

1. Keeping the url
2. Having a correct content-type

Both is unfortunately not possible

**Comment by Relequestual** [comment]
@awwright out of interest, why were they slected to not use extensions?

**Comment by Relequestual** [comment]
@awwright ping!

**Comment by awwright** [comment]
@Relequestual Filename extensions have a history of being left off URIs sometimes... idk if there was any rationale for it here, but it's something that's supposed to be supported by web servers and GitHub doesn't. <https://www.w3.org/Provider/Style/URI.html#remove> has some background.

A slightly more pressing issue is that we can't serve any file with `application/schema+json` regardless of what filename we pick.

**Comment by Relequestual** [comment]
I think that's a limitation on jekyll - it picks the content type based on the file extension, I believe. I read this somewhere recently

**Comment by handrews** [comment]
In the discussion on #32 everyone involved including the original poster seems to have agreed to close the PR and rethink this.

To recap, the reason for not having ".json" is to potentially offer other representations in the future, e.g. an `application/schema+cbor` encoding, via standard content-negotiation mechanisms.

For the standard meta-schemas, I'd argue that that's a very important thing.

For the demo schemas, I could see duplicating them with a .json extension with some sort of note that it is for convenience and not recommended as a best practice?  If it is just for the demo schemas, my only concern is giving the wrong impression of how schemas really should be served.  

Relying on file extensions is a personal pet peeve and I realize not everyone else feels as strongly, but the increasing popularity of CBOR, particularly with IoT, means that we will quite likely want to offer representations in multiple media types.  I think EXI for JSON has also been brought up.

Also paging @vossad01 given their extensive contributions to the PR discussion :-)

**Comment by awwright** [comment]
What if we just get an AWS Org and transfer the domain registration there (if we can)?

Then while we're there, we can host the website on AWS S3, which lets us set all the correct Content-Type headers, redirects, and other HTTP headers (CORS) that we like. And we can set a GitHub hook to automatically pull and build the website.

Billing would be minimal. I can easily take care of it. We could probably find a someone to sponsor it.

**Comment by Relequestual** [comment]
IF we can get hold of the domain, then sure, but as far as I'm aware, we still have no idea who owns the account. Maybe someone should contact the registra and explain the situation.

Be careful though on expected billings. Someone (Happy to if I have time) should set up analytics for the site... see how much traffic it actually gets. Could be more than you expect... maybe anyway.

---
Aside: Given how many bluechip companies are "members" of the Open API Inititaitve, I'm a bit dissapointed that we don't have any making comitments with JSON Schema.
I DID lay out a plan to contact various individuals, but I've so far only tried with MS, and haven't made much headway.

**Comment by handrews** [comment]
@awwright for the reasons @Relequestual mentions, I would prefer to accept this PR now and worry about hosting upgrades later.  This is an improvement in experience and it doesn't hurt anything.  Since these aren't the meta-schemas, it's not going to cause serious confusion if people choose to reference them with `.json`.  But the current situation is causing at least some problems, so let's go for "better" here and not "perfect but depends on a problem we have been unable to solve ***literally for multiple years now***".

**Comment by handrews** [comment]
("This PR meaning #104)

**Comment by Anthropic** [comment]
@Relequestual @kriszyp is the registered owner of the domain, his contact details come up in a whois search. I added #108 because I feel we should still provide the meta schema files with .json extension also. It just makes things easier for end users, even if you can get it to open as json, users still have to re-name the file if they want it as a json file in their operating system, why not provide an easy to work with option.

**Comment by handrews** [comment]
@Anthropic @kriszyp paid the account, which you can do without owning the account (no, we don't understand it either).  However, no one has the actual login credentials, so we can't change its configuration.

See https://github.com/kriszyp/json-schema/commit/1c4923479501cdf78c6dab4e9af4bb40dc7992f0#commitcomment-19914120 for @kriszyp's explanation.

Seriously, if we could do this we'd have done it already.

**Comment by vossad01** [comment]
I believe this can be closed since #104 was merged.

**Comment by Relequestual** [comment]
Agreed. @evert does that solution work for you?

**Comment by evert** [comment]
Works for me :)
