### ISSUE TITLE
Publisize the mebership in the org

### ISSUE THREAD

**Issue by epoberezkin** [json-schema-org/json-schema-org.github.io#33]
I know, I've raised it a couple of times, but it still didn't happen for some reason.

I think it would increase the confidence of new users (yes, there are plenty of people who are only discovering JSON-Schema) if they could see more than 2 owners of the organisation.

@Relequestual @kriszyp Who else? The old one has 6 people, there probably should be more now.

**Comment by Relequestual** [comment]
I didn't realise my membership wasn't public! Fixed for myself. I don't know if @kriszyp still wants to be involved to any degree. There's certinly scope for just a steering type role if that's what he would like.

**Comment by Relequestual** [comment]
@geraintluff also.

**Comment by Relequestual** [comment]
@epoberezkin I'd LOVE to see more people involved! Especially some figures with experience in this type of thing who can guide us... but @awwright is doing a pretty good job so far!

**Comment by awwright** [comment]
@epoberezkin That's up to individual team members to decide, there's nothing that we can really do about it here.

The best indicator of activity will be the listed authors on the I-D, I wouldn't use the GitHub membership for anything.

**Comment by epoberezkin** [comment]
I understand. I was hoping that some people who may have forgotten would do it. Let's close it then.

**Comment by Relequestual** [comment]
I had forgotten to do it! So it wasn't for nothing =]
