### ISSUE TITLE
The obsolete implementations page needs cleanup

### ISSUE THREAD

**Issue by jdesrosiers** [json-schema-org/json-schema-org.github.io#330]
While preparing a PR to add my implementation, I noticed that the obsolete implementations page needs some attention. A significant number of the implementations that show up on that page don't belong and are duplicated on the main implementations page. Someone might want to give that a quick look.

**Comment by philsturgeon** [comment]
Thanks for volunteering @jdesrosiers! There has been a little copy and paste in a few sections, I took care of editors last week but if you’ve spotted another section which needs sorting out we’d love a pull request!

The trick is to scour the README, docs or code to find out which drafts they support, then if it’s <= 4 you delete them from the main implementations page. If it’s >4 you delete them from the obsolete page and make sure they’re on the main implementations list! 

Doesn’t take long but requires some clear headspace to get the job done.

**Comment by jdesrosiers** [comment]
That's cute @philsturgeon :smile:, but this time my contribution is just to bring attention to the issue. I'll let someone else take it the rest of the way.

**Comment by philsturgeon** [comment]
Worth a try. One of our well-paid full time support team will take care of this for you immediately! 😉

**Comment by ldexterldesign** [comment]
Here are the duplicate items:

http://alpacajs.org
http://github.com/Limenius/liform-react
http://github.com/brutusin/json-forms
http://github.com/cloudflare/json-schema-tools/tree/master/workspaces/doca
http://github.com/ebdrup/json-schema-benchmark
http://github.com/joshfire/jsonform
http://github.com/json-schema-form/angular-schema-form
http://github.com/json-schema-org
http://github.com/json-schema-org/json-schema-org.github.io
http://github.com/makinacorpus/angular2-schema-form
http://github.com/mokkabonna/json-schema-compare
http://github.com/mokkabonna/json-schema-merge-allof
http://github.com/mozilla-services/react-jsonschema-form
http://github.com/networknt/react-schema-form
http://github.com/pboettch/json-schema-validator
http://github.com/schlothauer-wauer/DJsonSchema
http://github.com/schlothauer-wauer/jsoncodegen
http://github.com/swaggest/php-json-schema
http://github.com/swaggest/php-json-schema-bench
http://jsonforms.io

2 mins work 💅

Regards
