### ISSUE TITLE
Draft-06 schema should match latest GitHub source

### ISSUE THREAD

**Issue by ssilverman** [json-schema-org/json-schema-org.github.io#357]
I just noticed that the downloadable Draft-06 schema (https://json-schema.org/draft-06/schema from https://json-schema.org/specification-links.html#draft-6) doesn't match what's on GitHub: https://github.com/json-schema-org/json-schema-spec/blob/draft-06/schema.json

This is different:
```
        "patternProperties": {
            "type": "object",
            "additionalProperties": { "$ref": "#" },
            "propertyNames": { "format": "regex" },
            "default": {}
        },
```

`"propertyNames": { "format": "regex" },` is missing.

**Comment by Relequestual** [comment]
I'm not sure this change was correct in the first place.
https://github.com/json-schema-org/json-schema-spec/pull/704#issuecomment-703881009

**Comment by handrews** [comment]
`format` is open-ended so there are no invalid values.  Unknown value effectively serve as documentation.
