### ISSUE TITLE
404 in http://json-schema.org/shared.html

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-org.github.io#37]
Originally filed by @JulienPalard as json-schema/json-schema#197

shared.html has several 404 links

**Comment by Relequestual** [comment]
It no longer is a 404, but there is a lack of styling issues. Looks like something is wrong in terms of template building for this. Needs investigation.

**Comment by vossad01** [comment]
The original bug is that http://json-schema.org/geo.properties (which is linked from shared.html) gives a 404.

However, is *shared.html* still an intended page?  There are no links to the page from within the website.  Unless there are external links to it, the only way the page can be discovered it by looking at the Git repository.

**Comment by handrews** [comment]
@vossad01 good question.  I'm not even sure what the purpose of that page was, although I remember it existing on the old version of the site.  It seems like an embryonic registry for standardized schemas, but what level of management and upkeep should we be doing for such a thing while the drafts are under development?

As an aside, it is great to see someone paying some attention to the web site.  We've known that it needs attention but the active members have been spending our time on the spec and have not had much left over to update the web site.  Please keep filing issues and submitting PRs :-)

**Comment by vossad01** [comment]
All of the links from *shared.html* can be seen under [Docs/Standard Schemas](json-schema.org/documentation.html#standard-schemas) except for "schema" (which I understand to be a schema for JSON Schema).

It seems most relevant to decide if [schema](https://github.com/json-schema-org/json-schema-org.github.io/blob/master/schema) should be linked, add it with the others if it should, and delete *shared.html*

___
Are these schemas "blessed" by this project?  Is the project concerned with establishing standardized schema in the JSON Schema standard, or just in establishing JSON Schema?  The heading "Standard schemas" suggest they are.

If there is nothing special about these particular specimens, I suggest the section be renamed and moved to the "Examples" page.
