### ISSUE TITLE
Slack link expired

### ISSUE THREAD

**Issue by m-mohr** [json-schema-org/json-schema-org.github.io#372]
The Slack links are all expired and thus I can't join the Slack.

**Comment by Relequestual** [comment]
Which link did you click? Seemed to work for me.

**Comment by m-mohr** [comment]
All 3 of them on the front page, they direct me to Slack but once I have chosen my Google account it says that the invitation has expired.

**Comment by Relequestual** [comment]
Here's the link for your access: https://join.slack.com/t/json-schema/shared_invite/zt-8o78yech-XtsW6g9hrqe0SVq94Jim8Q
If you have time, please make a PR to update the link on the site, or just leave this issue open =]

**Comment by m-mohr** [comment]
Thank you, but this link is also expired for me...

**Comment by Relequestual** [comment]
Weird. This is a fresh link and works for me.
Maybe there is some issue with your google account?
Maybe you could try that link in an incognito tab in case there's some issue with some session data or something?

**Comment by m-mohr** [comment]
I've tried all 3 of my user accounts, also now in Incognito mode. Still, Slack says it's expired. Not sure what else could go wrong on my side.

**Comment by Relequestual** [comment]
I've reached out to Slack support. =/

**Comment by Relequestual** [comment]
They have confirmed there's a known bug and are working on fixing it... Super!
Feel free to DM me on twitter in the mean time =]

**Comment by m-mohr** [comment]
Thanks! It seems the slack link is still "expired". Any news on this? Otherwise, I'll likely dm you with a question tomorrow. ;-)

**Comment by Relequestual** [comment]
I haven't heard anything further from Slack, other than they are aware of the bug and are working on it.
Feel free to reach out to Slack support too!

Feel free to DM me with questions =D

**Comment by karenetheridge** [comment]
am I reading this correctly that no one can join the slack? They shouldn't need an invite link -- just use the "json-schema" space when prompted, because our channels are public.

**Comment by Relequestual** [comment]
@karenetheridge No. There is an issue where some people can't use the invite, and I don't know what the situation is.
The invite link works (Slack are aware. It works for "most people" they say).

I believe join based on lookup only works if you define a domain name and they use that email address, for paid accounts.
If you can find anything that shows people don't need an invite, we can make changes, but that's as I understand the status-quo.

**Comment by jsoref** [comment]
For reference, the default expiration for Slack invite links is 30 days. An admin can edit the link settings and set the link to never expire (it will still expire after 2000 users use the link).
https://slack.com/help/articles/201330256-Invite-new-members-to-your-workspace#share-an-invitation-link

**Comment by Relequestual** [comment]
Thanks. I'm aware of this.
When I contacted slack, there was an actual problem, and the link wasn't expired.
Since contacting them, it seems it has expired. The link has now been replaced.
