### ISSUE TITLE
Web site needs updating with new drafts/meta-schema

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-org.github.io#38]
@stefk noted in json-schema/json-schema#198 that the web site still shows the Draft 04 specifications and meta-schemas.  @awwright I imagine you're already on this but filing as @stefk wanted to still track this after closing the issue at the old repo.

**Comment by Relequestual** [comment]
Need updating at http://json-schema.org/documentation.html also

**Comment by Relequestual** [comment]
I'd like to close this in favour of https://github.com/json-schema-org/json-schema-org.github.io/issues/51

**Comment by awwright** [comment]
Yeah, it appears #42 covered this

**Comment by handrews** [comment]
As noted above, this is covered elsewhere.
