### ISSUE TITLE
2020-12 vocabulary schemas should be in vocab/ and not in meta/

### ISSUE THREAD

**Issue by ssilverman** [json-schema-org/json-schema-org.github.io#381]
This way the URI matches the URL on the site.

This issue affects `specification.md` and the vocabulary schema locations.

**Comment by ssilverman** [comment]
I see. This confused me for a little bit, I think I get the intent of the reasoning you mention.

**Comment by handrews** [comment]
As @gregsdennis noted, this is correct as-is.  One day hopefully we'll have machine-readable vocabulary files.
