### ISSUE TITLE
Updated library requires ruby 2.5 which is not provided by default in Travis-ci

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-org.github.io#388]
The linked CVEs show the issue is related to processing XML resulting in a potential DoS.
I don't think this concerns us.

Additionally, the newer version of nokogiri requires ruby 2.5 or above, which is not provided by Travis-ci by default.
We should look into how to request a higher version of ruby.

@dependabot ignore this minor version

_Originally posted by @Relequestual in https://github.com/json-schema-org/json-schema-org.github.io/issues/387#issuecomment-821075164_

**Comment by notEthan** [comment]
not sure why you say travis does not provide ruby >= 2.5 - it does. ruby 2.7 is current and 2.5 is EOL.

**Comment by Relequestual** [comment]
I missunderstand this line then: https://travis-ci.org/github/json-schema-org/json-schema-org.github.io/builds/767303313#L409

Can we specify we want a differnet version of ruby than those listed?

**Comment by Relequestual** [comment]
Given Travis-ci.org is now closed, we should close this issue and create a new one looking to move the CI tests to GitHub actions.
