### ISSUE TITLE
Does GA use tracking cookies that would require us to include an annoying GDPR notification of some sort?

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-org.github.io#402]
> Does GA use tracking cookies that would require us to include an annoying GDPR notification of some sort? - @jdesrosiers

This is a good question. I'm going to seek advice from OpenJS Foundation on this one.
This would apply for the main site also.

_Originally posted by @Relequestual in https://github.com/json-schema-org/understanding-json-schema/issues/171#issuecomment-888916564_

**Comment by Relequestual** [comment]
We might consider using free tooling to resolve this if required: https://www.onetrust.com/products/cookie-consent/

**Comment by benjagm** [comment]
Closed as we started to use Plausible.
