### ISSUE TITLE
`Request Id: 1ffc7204-0b42-46c2-ae94-89ba457f4300 Correlation Id: aabc9e9b-f97a-4639-9236-d0546db5d0fb Timestamp: 2021-07-30T02:34:03Z Message: AADSTS50020: User account 'ramboo.chi@hotmail.com' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application 'f44b1140-bc5e-48c6-8dc0-5cf5a53c0e34'(Microsoft Edge) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.`

### ISSUE THREAD

**Issue by Text-only** [json-schema-org/json-schema-org.github.io#404]
`Request Id: 1ffc7204-0b42-46c2-ae94-89ba457f4300 Correlation Id: aabc9e9b-f97a-4639-9236-d0546db5d0fb Timestamp: 2021-07-30T02:34:03Z Message: AADSTS50020: User account from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application 'f44b1140-bc5e-48c6-8dc0-5cf5a53c0e34'(Microsoft Edge) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.`

_Originally posted by @Text-only in https://github.com/json-schema-org/json-schema-org.github.io/issues/399#issuecomment-889593968_

**Comment by Text-only** [comment]
#399 
▪︎**Automatically—generated–by AZURE_WEBAPP_PACKAGE_PATH**

**Comment by Relequestual** [comment]
User has been blocked.
