### ISSUE TITLE
Implimentations listing missing Clojure's scjsv

### ISSUE THREAD

**Issue by code-ape** [json-schema-org/json-schema-org.github.io#41]
Clojure has a library for doing JSON Schema validation and I thought I would mention it since it's not listed on the implementations page :)

https://github.com/metosin/scjsv

Cheers,
code-ape

**Comment by Relequestual** [comment]
Great! Thanks @code-ape , Please feel free to make a pull request!

**Comment by Relequestual** [comment]
Merged.
