### ISSUE TITLE
Implementation: JSON Essentials

### ISSUE THREAD

**Issue by pinery-systems** [json-schema-org/json-schema-org.github.io#415]
Hi,

I've followed your directions for adding a new implementation to the web-site and created a pull request about a month ago, since the no reaction at all, it's neither reject nor accepted. It's called [JSON Essentials](https://pinery.systems/json-essentials-com/index.html), and as of today it supports Drat-07 and passes all required and some optional tests from the test suite, so to my understanding it should satisfy all requirements for being included in the list of implementations. In case you've seen it and did not approve because it does not satisfy any requirements, please clarify those requirements then.

There is one thing about its category though, unlike any other implementation, it's not language specific, in fact it can be used in almost all programming languages on the Windows platform because it's an COM component, that's why I've also added the COM/ActiveX category as it would be wrong to include it into any other language specific category.

Thanks,
   Alexander

**Comment by Relequestual** [comment]
Hey Alexander. Huge apologies that your PR has been left hanging.
I'll make sure someone gets to it this week, even if it's me! =]

**Comment by gregsdennis** [comment]
PR in question is #411

**Comment by gregsdennis** [comment]
Hello @pinery-systems.  I've had a look at the PR.  The content looks fine.

Would you be able to provide test results?  Typically the libraries we add to the site are open-source, and so the results are easy to find.  We just want to make sure we're properly curating our list.

Thanks.

(Also, I'm unable to merge in this repo, so I'll have to defer to someone else on the team to push the button.)

**Comment by pinery-systems** [comment]
Thanks for looking into it!

Yes, it's not open source, but the test projects and scripts are included into the re-distributable package with the source code.
I have included the results of the execution of the test suite test cases.

I assume you might want to try it to verify, if so then you can either download the evaluation version from the web-site or submit a request for a free personal copy. The evaluation page explains simple installation instructions, after it's installed you will only need to run `test.cmd > results.txt` in order to output all results into the text file. It'll include all results however, the test suite test cases can be found by `test_suite.draft7` string.

In case you'll need to run all test suite test cases only then in the _tests\wsh_ directory run:
`cscript.exe test_all.wsf --verbose --run=test_suite.draft7 --license-token=jesscomeval > results.txt`

And if case you'll need to check those tests are executed you can find it in quite a small and simple file _tests\wsh\test_schema_suite.js_.

Let me know if you'll need any additional information. Thank you.

Regards,
   Alexander
[test-results.txt](https://github.com/json-schema-org/json-schema-org.github.io/files/7190669/test-results.txt)

**Comment by pinery-systems** [comment]
Hi, it's been a while since I'd provided the test results. Was it what you needed to see and was it enough?

**Comment by gregsdennis** [comment]
Sorry.  We discussed it for a bit, then our collective attention was pulled elsewhere. I don't see a problem with this PR.  But I don't have rights to merge here.

**Comment by pinery-systems** [comment]
No problem. I can see now that the PR has been just approved. Will wait to see it live. Thank you

**Comment by Relequestual** [comment]
Apologies for the crazy long delay in merging your PR. It is now merged.
