### ISSUE TITLE
jsonld playground does not work with remote contexts anymore

### ISSUE THREAD

**Issue by bertvannuffelen** [json-schema-org/json-schema-org.github.io#426]
Example https://w3c.github.io/json-ld-syntax/#example-sourcing-a-context-in-a-type-scoped-context-and-setting-it-to-propagate

does not work anymore. An internal error is reported: Could not load content for webpack://[name]/jsonld.min.js (HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME).

kr,

Bert

**Comment by Relequestual** [comment]
I think you've arrived at the wrong repo @bertvannuffelen.
This repo contains the website for the JSON Schema project. It is unrelated to JSON-LD.
