### ISSUE TITLE
Add link to youtube

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-org.github.io#473]
Header?
Header and footer?

We have a URL https://www.youtube.com/c/JSONSchemaOrgOfficial

**Comment by gregsdennis** [comment]
If we put it in the header, I suggest changing the "join our slack" to just the slack logo and then adding this as just the youtube logo.

It should also have a button in the "What now?" section.

**Comment by benjagm** [comment]
Completed in the new website.
