### ISSUE TITLE
Domain name "json-schema.org" disappeared

### ISSUE THREAD

**Issue by mathroc** [json-schema-org/json-schema-org.github.io#48]
This is a copy of json-schema/json-schema#250 (because the repo si marked as archived)

> Today (21 November 2016) I discovered that I cannot open website "json-schema.org" due to missing DNS records. I remember on Friday 18th it was still there, I am not sure about the weekend, though.
> 
> Is this a deliberate, planned transition, or just someone forgot to pay for the domain registration?
> 
> The problem is that some validation tools (e.g. jayschema) that can chain schemas during validation, rely on referred schemas being reachable on the URL specified in id attribute. Obviously, http://json-schema.org/schema, being the ultimate root of all other schemas, will break such validation if not present.
> 
> Is there anything I can do to fix this?
— @radio-miskovice

**Comment by Relequestual** [comment]
Thanks @mathroc, @radio-miskovice,

We are aware of an existing domain expiration problem. =[
We are trying to get in contact with the only individual who has access to transfer or pay for it.
There is an associated issue or PR with comments, but I can't locate it right now.

cc @json-schema-org/web-team @json-schema-org/spec-team @handrews

**Comment by Relequestual** [comment]
Found it: https://github.com/kriszyp/json-schema/commit/1c4923479501cdf78c6dab4e9af4bb40dc7992f0

**Comment by handrews** [comment]
@garycourt (just in case he might see the title here if he missed the notification on the other one)

**Comment by mathroc** [comment]
looks like the website is back online :)

**Comment by Relequestual** [comment]
Wonder who paid the bills!? =D

**Comment by mathroc** [comment]
@Relequestual stop wondering: https://github.com/kriszyp/json-schema/commit/1c4923479501cdf78c6dab4e9af4bb40dc7992f0#commitcomment-19914120

**Comment by dewiniaid** [comment]
From my reading of both the other issue and this one, am I correct in that nobody associated with the project actually has access to the domain name at current and it's just a case of the registrar not caring who pays the bills?

If so, should an issue be raised about fixing that?

**Comment by handrews** [comment]
@dewiniaid the problem is that the original person/people who set up this project and json-schema.org and have the admin accounts for the domain and the old github repo are gone and not responding to efforts to contact them.  :-(
