### ISSUE TITLE
Editors section removed from Software page

### ISSUE THREAD

**Issue by Clemens-U** [json-schema-org/json-schema-org.github.io#50]
Hi! There is no editors section anymore on the page implementations.html. Is this by intention or just by an oversight?
 
The following commit removed the editors section: "Remove old website generation mechanism", Sept 19, 2016, 4a5a039fbc2ce7f05174aa6845dcd78161089e9f

The section included tools like Visual Studio, ReSharper and JSONBuddy.
(Yes, I'm the author of JSONBuddy)

**Comment by Relequestual** [comment]
Thanks @Clemens-U - I'm pretty sure this was by mistake.
If you're able to make a pull request to put it back, that would be great. Otherwise, I'll pick up this issue when I can.

**Comment by Clemens-U** [comment]
I will add a pull request to restore all previous entries from the editors section. Thanks a lot!

**Comment by awwright** [comment]
@Clemens-U I've got you covered, see PR #53

**Comment by Clemens-U** [comment]
@awwright Thanks a lot! So I can close this issue :)
