### ISSUE TITLE
Should the glossary rename "draft" to "dialect"?

### ISSUE THREAD

**Issue by jviotti** [json-schema-org/json-schema-org.github.io#506]
See https://json-schema.org/learn/glossary.html#draft

**Comment by Julian** [comment]
I don't think the two are precisely the same, neither technically nor colloquially -- and I think "draft" is still in wide colloquial use -- the PR in #484 though adds an entry for `dialect` as well though. Going to mark this as also being closed by that PR but obviously chime in if you disagree.
