### ISSUE TITLE
Revise JSON Schema footer

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/json-schema-org.github.io#508]
Having added the [OpenJS Foundation footer content](https://github.com/json-schema-org/json-schema-org.github.io/pull/505), we should probably revise the project specific footer section.

we should probably remove the link to the google group, and include a link to our Code of Conduct.

Any other content anyone thinks we should add there? What do you expect to see but don't?

**Comment by benjagm** [comment]
Completed in the new website.
