### ISSUE TITLE
Create a page listing every single specification document

### ISSUE THREAD

**Issue by seagreen** [json-schema-org/json-schema-org.github.io#54]
I don't think this necessarily should be the main docs link (though we're also discussing how to improve that [here](https://github.com/json-schema-org/json-schema-org.github.io/issues/51), but I think it would be good to have a page somewhere on the site that lists the links to every single specification (including Core, Validation, etc) and links to the changelog(s) within those documents.

**Comment by Relequestual** [comment]
I was thinking the same a few days ago also. Points to you for opening the issue. Happy to accept a PR on this one!

**Comment by seagreen** [comment]
> Happy to accept a PR on this one!

I'm just here for QA, sorry=)

**Comment by seagreen** [comment]
I've collected the links (with help) in the wiki here: https://github.com/json-schema-org/json-schema-spec/wiki/Specification-Links

**Comment by handrews** [comment]
@Relequestual is the wiki page enough?  I thought we wanted this on json-schema.org itself?
