### ISSUE TITLE
Add section on role of hyper-schema in APIs

### ISSUE THREAD

**Issue by handrews** [json-schema-org/json-schema-org.github.io#63]
This issue is inspired by @davidjamesstone's questions in json-schema-org/json-schema-spec#201 about using JSON Schema to validate HTTP API headers.

We should add some content to the web site on best practices for APIs, and what JSON Hyper-Schema does and doesn't do.  Summarizing comments in that issue from @awwright and myself, some ideas include:

* The different roles of JSON Hyper-Schema (a media type) vs Service Definition formats such as OpenAPI.
* Why many things in service definitions are not necessarily required for REST when JSON Hyper-Schema is used correctly
    * Why you don't need to specify GET/PUT/PATCH/DELETE or POST-to-create explicitly
    * How to use link relations to convey usage (the "collection" and "item" relations come to mind as an easy example)
    * Assuming json-schema-org/json-schema-spec#179 goes into draft 6, how to use `schema` to indicate a non-standard POST
    * How to use `encType` to indicate PATCH by specifying a patch media type
* What is intentionally left out of hyper-schema? (assuming these continue to be outside of it), and how to think about these things in relation to hyper-schema?
    * auth
    * headers

I can take a first pass at this.  I need to sort it all out in my head as I'm writing my generic hyperclient anyway.

**Comment by Relequestual** [comment]
This is very interesting. I spent half a day or so looking at the HTML format documentation thing that guy in your company wrote, but now I consider that I won't really be able to fully specify the API I'm working on... I have to re-evaluate my thoughts. Maybe I don't understand the point of / reason for HyperSchema as much as I thought I did.

**Comment by handrews** [comment]
@Relequestual Anything in particular that you're now worried about not being able to specify?  Either in general with hyper-schema (in which case put it here) or in the documentation tool (in which case please file more doca issues- I'll be looking at it next week, actually).  doca currently uses some custom keywords to add stuff like header support, and while the way that's done might change a bit, I expect to continue to support documenting such things.

**Comment by Relequestual** [comment]
@handrews That's really interetsing, and exciting that you'll be looking at doca again shortly!

Mainly worried about not being able to define headers. Otherwise I mostly like doca. I should really file a few issues over there. I'd be happy to help out if I can! May fall within my day job task remit over the next few months! =D

**Comment by handrews** [comment]
A lot of this has been handled in the rewrite of hyper-schema for draft-07.  I'm going to close this and we can collect individual issues on which parts need further expansion on the web site.

Everything except for explicitly discussing OpenAPI/api description vs hypermedia is directly addressed in draft-07, and the nature of hyper-schema as hypermedia is discussed without reference to OpenAPI.  So the original scope here is pretty solidly covered.
