### ISSUE TITLE
Update example name

### ISSUE THREAD

**Issue by fulldecent** [json-schema-org/json-schema-org.github.io#70]
This regards [examples.html](examples.html) and perhaps other examples.

I am just starting to learn about JSON Schema and read the first example:

```json
{
	"title": "Example Schema",
	"type": "object",
	"properties": {
		"firstName": {
			"type": "string"
		},
		"lastName": {
			"type": "string"
		},
		"age": {
			"description": "Age in years",
			"type": "integer",
			"minimum": 0
		}
	},
	"required": ["firstName", "lastName"]
}
```

The `title` attribute is defined in http://json-schema.org/latest/json-schema-validation.html#rfc.section.6.1 as:

> [This keyword] can be used to decorate a user interface with information about the data produced by this user interface.

In light of this, the example's `title` seems incorrect because it is describing the schema itself rather than the JSON instance that is being validated.

## Recommended change:

    "title": "Person",

**Comment by fulldecent** [comment]
Per `git grep '"title": "' | cat` following are all places to consider an update:

 - [ ] draft-04/hyper-schema:    "title": "JSON Hyper-Schema",
 - [ ] draft-04/hyper-schema:            "title": "Link Description Object",
 - [ ] draft-04/links:    "title": "Link Description Object",
 - [ ] draft-zyp-json-schema-03.xml:	"title": "Product",
 - [ ] draft-zyp-json-schema-04.xml:    "title": "Product",
 - [ ] example1.html:    "title": "Product",
 - [ ] example1.html:    "title": "Product",
 - [ ] example1.html:    "title": "Product",
 - [ ] example1.html:    "title": "Product",
 - [ ] example1.html:    "title": "Product",
 - [ ] example1.html:    "title": "Product set",
 - [ ] example1.html:        "title": "Product",
 - [ ] examples.html:	"title": "Example Schema",
 - [ ] hyper-schema:    "title": "JSON Hyper-Schema",
 - [ ] hyper-schema:            "title": "Link Description Object",
 - [ ] latest/json-schema-core.html:    "title": "root",
 - [ ] latest/json-schema-core.html:        "title": "array item"
 - [ ] latest/json-schema-hypermedia.html:    "title": "Written Article",
 - [ ] latest/json-schema-hypermedia.html:            "title": "Article Identifier",
 - [ ] latest/json-schema-hypermedia.html:            "title": "Article Title",
 - [ ] latest/json-schema-hypermedia.html:            "title": "Article Illustration (thumbnail)",
 - [ ] latest/json-schema-hypermedia.html:    "title": "Example data",
 - [ ] latest/json-schema-hypermedia.html:    "title": "Schema defining links",
 - [ ] links:    "title": "Link Description Object",

I am checking off each one that is reviewed as correct.

**Comment by fulldecent** [comment]
Pull request #71 fixes the first issue. Nearly everything else is OK. 

Perhaps this example could also be more descriptive: https://github.com/json-schema-org/json-schema-org.github.io/blob/master/latest/json-schema-core.html#L590-L596

```json

{
    "title": "root",
    "items": {
        "title": "array item"
    }
}
```

**Comment by handrews** [comment]
@fulldecent see 
json-schema-org/json-schema-spec#136 (general discussion of documetation keywords)
json-schema-org/json-schema-spec#197 (propossed `"$coment"` to prevent people from using `"title"` as a comment)

I feel like there are some more issues along these lines but I can't find them right now (there are several regarding default, but fewer regarding title and description).

Basically, there's not agreement on what these keywords are really for.  Some current project members regularly quote definitions that do not agree with the spec.  I'm hoping we can address this soon after we get Draft 06 out the door.

For now I would call this blocked on the general confusion over what we are doing with annotation/documentation/comments.

**Comment by Relequestual** [comment]
@fulldecent Really appreciate your effort on this. I'm not as reserved as @handrews on this one, but if he says we should wait, then we should.

**Comment by fulldecent** [comment]
Thank you. Next PR coming to fix the remaining one.

**Comment by fulldecent** [comment]
Done. That is the last remaining one.
