### ISSUE TITLE
Use unique titles

### ISSUE THREAD

**Issue by nealmcb** [json-schema-org/json-schema-org.github.io#93]
Thanks for your site - very helpful!

It would be easier to manage tabs, bookmarks, etc if the HTML titles of pages were unique. But now, e.g., these two pages just have the title "JSON Schema".

- http://json-schema.org/
- http://json-schema.org/example2.html

**Comment by Relequestual** [comment]
Hey @nealmcb - Sure. Happy to accept PRs on this.

**Comment by nealmcb** [comment]
Great, thanks.  Tips on the right place and best way to do this would also be welcome :)

**Comment by vossad01** [comment]
@nealmcb You would specify the title in the [YAML front matter](https://jekyllrb.com/docs/frontmatter/) you may need to additionally change the `page` type to avoid the title appearing on the page.

@Relequestual This is pretty much guaranteed to conflict with #85.

**Comment by Relequestual** [comment]
@vossad01 Agreed. Thanks for picking this up.

@nacmartin Mind holding off till #85 is resolved?
In terms of right place and best way, currently it's just make a PR against master with the website.

**Comment by nealmcb** [comment]
Assuming you meant to refer to me - no rush. Just seems like a good idea.

**Comment by Relequestual** [comment]
Sorry @nealmcb! yeah. I agree it's a good idea.

**Comment by nealmcb** [comment]
Awesome - thanks!
